### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by alecmchiu** [aritra90/TeraPCA#1]
I am trying to run TeraPCA on a large data. It throws a segmentation fault when trying to read the BED file. The BED file works fine with other methods such as PLINK (it was generated through PLINK filtering).

```
[alecmchiu]$ TeraPCA -bfile filtered_snp
filtered_snp
[Wed Aug 14 16:15:23 2019] Reading .fam file: filtered_snp.fam

[Wed Aug 14 16:15:25 2019] Opened .bim file: filtered_snp.bim
Size of RAM (in KB): 1056530212

Number of rows per block: 26974

[Wed Aug 14 16:15:26 2019] Reading .bed file: filtered_snp.bed by blocks.
Segmentation fault
```

I recompiled the binary and the same issue occurs. The dataset is 488,363 x 146,671.

Both the recompiled version and the version that comes with the repository work fine on the example data.

**Comment by aritra90** [comment]
Hi @alecmchiu 

Sorry that you have ran into such an issue. Just a quick look at the dimensions, I realized that a matrix block multiplication in your case would require 13 GB of RAM. That might be a reason for the segmentation fault. Can you try doing the same but specify the number of rows to something small, such as 1K - 5K per block (by --rfetched) and let me know if that works. 

The package is automated to handle "large p, small n" underdetermined systems. In your case you have more individuals than SNPs so that's why we need to tweak the --rfetched to obtain the desired computation.

**Comment by alecmchiu** [comment]
Hi @aritra90, thanks for getting back to me. I tried altering the --rfetched parameter to 1000 and 5000, but it continues to throw a segmentation fault at the same step.

**Comment by aritra90** [comment]
Hi @alecmchiu 

Thanks for the patience and trying it out. Sorry that it didn't work. 
Is the number of PCs set to default (10) ? If that is the case you can change -nrhs to around 15 to see if that works. 
I tried this on a simulated dataset matching same dimension and it works fine on my end. This is a memory allocation issue and the allocated memory is of order the block size * nrhs * 8 (for double). Hence these are the dimensions that you need to tweak.  I will be trying on other datasets to see if I see any discrepancy and update you if I find anything.

**Comment by alecmchiu** [comment]
@aritra90 

Thank you for all your help. I was only estimating 5 PC's, but after playing around with the parameters you mentioned, I was able to successfully get the output!

I will close the issue now. Thanks again!
